### ISSUE TITLE
polyglotI18nProvider(() => ChineseMessages, 'zh')中的zh配置不对，需要使用ch或者zh_CN

### ISSUE THREAD

**Issue by jinguo-yin** [haxqer/ra-language-chinese#1]
如果按照reademe.md中配置为zh，在选择删除时不论多少行都会显示选中1行，修改为ch或者zh_CN后显示正常

**Comment by haxqer** [comment]
done ~~
Thank you for your reminder. 
It has been updated to 4.16.2.
